# Project
version=1.0.0
group=com.example.examplemod
java_version=21

# Common
minecraft_version=1.21.10
mod_name=ExampleMod
mod_author=Tslat
mod_id=examplemod
license=MIT
credits=
description=Multiloader GeckoLib test mod
minecraft_version_range=[1.21.10, 1.22)
neo_form_version=1.21.10-20251007.142004
parchment_minecraft=1.21.9
parchment_version=2025.10.05
geckolib_version=5.3-alpha-3

# Fabric
fabric_version=0.134.1+1.21.10
fabric_loader_version=0.17.2

# Forge
forge_version=60.0.3
forge_version_range=[60.0.0,)
forge_loader_version_range=[60,)

# NeoForge
neoforge_version=21.10.10-beta
neoforge_loader_version_range=[5,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
