# Project
version=1.0.0
group=com.example.examplemod
java_version=25

# Common
minecraft_version=26.1-snapshot-7
mod_name=ExampleMod
mod_author=Tslat
mod_id=examplemod
license=MIT
credits=
description=Multiloader GeckoLib test mod
minecraft_version_range=[26.1,)
neo_form_version=26.1-snapshot-7-1
geckolib_version=5.5-test-2

# Fabric
fabric_version=0.143.5+26.1
fabric_loader_version=0.18.4

# Forge
forge_version=61.0.3
forge_version_range=[61.0.0,)
forge_loader_version_range=[61,)
forge_eventbus_validator_version=[7.0-beta.10,)

# NeoForge
neoforge_version=26.1.0.0-alpha.12+snapshot-7
neoforge_loader_version_range=[5,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false