# Project
version=1.0.0
group=com.example.examplemod
java_version=21

# Common
minecraft_version=1.21.8
mod_name=ExampleMod
mod_author=Tslat
mod_id=examplemod
license=MIT
credits=
description=Multiloader GeckoLib test mod
minecraft_version_range=[1.21.8, 1.22)
neo_form_version=1.21.8-20250717.133445
parchment_minecraft=1.21.8
parchment_version=2025.07.20
geckolib_version=5.2.2

# Fabric
fabric_version=0.132.0+1.21.8
fabric_loader_version=0.17.2

# Forge
forge_version=58.0.9
forge_version_range=[58.0.9,)
forge_loader_version_range=[58,)

# NeoForge
neoforge_version=21.8.36
neoforge_loader_version_range=[5,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
