plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.0,)'
    id 'net.minecraftforge.accesstransformers' version '[5.0.1,)'
}
base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir("run/${name}")
            systemProperty("forge.logging.console.level", "debug")

            //args "--mixin.config=${modId}.mixins.json"
        }

        register("client") {qw
            args "--username", "Dev"
        }

        register("client2") {
            args "--username", "Dev2"
        }

        register("server") {}
    }
}

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    exclusiveContent {
        forRepository {
            maven {
                name = "Sponge"
                url = uri("https://repo.spongepowered.org/repository/maven-public")
            }
        }
        filter {
            includeGroupAndSubgroups("org.spongepowered")
        }
    }
    mavenCentral()
    mavenLocal()
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    implementation minecraft.dependency("com.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    annotationProcessor "net.minecraftforge:eventbus-validator:${forge_eventbus_validator_version}"
}
sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}